// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA99iUERPiDet70pGGTUyspFG8Exf3_qRI',
    appId: '1:1090761232953:web:438af5377bd7eb6146f3e8',
    messagingSenderId: '1090761232953',
    projectId: 'jutenotifications',
    authDomain: 'jutenotifications.firebaseapp.com',
    storageBucket: 'jutenotifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMz0tZhXzNJTRgOUZxRMYbjbx04e7h8A',
    appId: '1:1090761232953:android:aac1430b75a47c7346f3e8',
    messagingSenderId: '1090761232953',
    projectId: 'jutenotifications',
    storageBucket: 'jutenotifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9w6l0ouNF38ANrTlEjBNJT7EBCrKbiU',
    appId: '1:1090761232953:ios:13ae363d9d1aad0246f3e8',
    messagingSenderId: '1090761232953',
    projectId: 'jutenotifications',
    storageBucket: 'jutenotifications.firebasestorage.app',
    iosBundleId: 'com.example.juteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9w6l0ouNF38ANrTlEjBNJT7EBCrKbiU',
    appId: '1:1090761232953:ios:13ae363d9d1aad0246f3e8',
    messagingSenderId: '1090761232953',
    projectId: 'jutenotifications',
    storageBucket: 'jutenotifications.firebasestorage.app',
    iosBundleId: 'com.example.juteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA99iUERPiDet70pGGTUyspFG8Exf3_qRI',
    appId: '1:1090761232953:web:f7f5a517a0a4209446f3e8',
    messagingSenderId: '1090761232953',
    projectId: 'jutenotifications',
    authDomain: 'jutenotifications.firebaseapp.com',
    storageBucket: 'jutenotifications.firebasestorage.app',
  );
}
